# Generated by Django 4.0.4 on 2022-05-19 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_like'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LikeButton',
        ),
    ]
